name: SnowBalls
main: com.guntherdw.bukkit.SnowBalls.SnowBalls
depend:
   - TweakcraftUtils
version: 2.0
commands:
    snowballs:
        description: ClientMod interface
        usage: /<command> client