name: SnowBalls
main: com.guntherdw.bukkit.SnowBalls.SnowBalls
soft-depends: [TweakcraftUtils]
version: 2.5
commands:
    snowballs:
        description: ClientMod interface
        usage: /<command> [client|reload]