name: SnowBalls
main: com.guntherdw.bukkit.SnowBalls.SnowBalls
depend:
   - TweakcraftUtils
version: 1.5
commands:
    snowballs:
        description: ClientMod interface
        usage: /<command> client